name = "maruya-streaming-player"
compatibility_date = "2024-08-06"
pages_build_output_dir = "dist/public"

[build]
command = "npm run build"
cwd = "."
watch_dir = "client"

[env.production.vars]
NODE_ENV = "production"